### ISSUE TITLE
Keep tech does not add range

### ISSUE THREAD

**Issue by robert-denney** [SiegeEngineers/aoe2techtree#114]
https://github.com/SiegeEngineers/aoe2techtree/blob/8fa42908a1790565f666076675b5d7f155cbdf47/data/locales/en/strings.json#L640

Watch towers, guard towers, and keeps all have 8 range. The description for the keep upgrade (string 28063) says `...build Keeps, which are stronger and have more attack strength, range, and armor`, I believe this is incorrect.

**Comment by HSZemi** [comment]
Hi,
and thank you for bringing this up! It appears you are correct.

We are verbatim using the data from the game files for translations. (That includes English.) That is kind of a necessity, since we cannot really support and keep up with 17 different languages otherwise.

It would therefore probably be best to report this inaccuracy in the [official Age of Empires forums](https://forums.ageofempires.com/c/age-of-empires-ii/aoe2-de-bugs/102) to get it fixed in the game itself. Once that happened, aoe2techtree will incorporate the fix automatically.

**Comment by robert-denney** [comment]
<3 good news

**Comment by adrianopol** [comment]
Hello, got you, thanks for advice!
