### ISSUE TITLE
Goth infantry cost

### ISSUE THREAD

**Issue by HourGlss** [SiegeEngineers/aoe2techtree#140]
Racial bonus not taken into account it seems.

**Comment by HSZemi** [comment]
This is essentially https://github.com/SiegeEngineers/aoe2techtree/issues/65.

In order to implement that functionality properly, we'd have to emulate a big chunk of the game logic when it comes to applying techs and effects. This is certainly doable, but I do not currently have the capacity to implement it. Feel free to do it yourself and create a pull request though :slightly_smiling_face:
