### ISSUE TITLE
Translation mistake in simplified Chinese

### ISSUE THREAD

**Issue by Epiphanye30** [SiegeEngineers/aoe2techtree#141]
The unit tech 'Hussite Reform' of Bohemian is currently translated wrong, and actually means the opposite of English version. It should be ' 僧侣和修道院科技消耗的黄金，由食物替代' instead.

**Comment by HSZemi** [comment]
Thank you for your bug report!

We are verbatim using the data from the game files for translations. That is kind of a necessity, since we cannot really support and keep up with 17 different languages otherwise. 

What you reported is indeed an issue in the original game files.

It would probably be best to report this bug in the [official Age of Empires forums](https://forums.ageofempires.com/c/age-of-empires-ii/aoe2-de-bugs/102) to get it fixed in the game itself. Once that happened, aoe2techtree will incorporate the fix automatically.

It [worked before](https://github.com/SiegeEngineers/aoe2techtree/issues/114) :sweat_smile:
