### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by drewgon** [SiegeEngineers/aoe2techtree#24]
Hi, I was trying to view this on a mobile while killing some time today.
I was unable to select other Civ's aside from the default Aztec as i couldnt see the drop down.

Thanks for this website tho its awesome!

**Comment by HSZemi** [comment]
I can confirm this issue, but do not know why the top bar is not displayed on mobile browsers.

We are currently planning to move the civ selection to the sidebar anyway (https://github.com/SiegeEngineers/aoe2techtree/pull/22), so the issue should be resolved soon™.

In the meantime, you can open any unit/building/tech by tapping on it, and from there tap the icon of the civilisation that you want to view, hereby changing the currently displayed civilisation.

**Comment by drewgon** [comment]
Thanks HSZemi,

Pitty I dont know the Symbols haha

**Comment by HSZemi** [comment]
The civ selection has been moved and I also tried to improve handling on mobile devices. It should be better now.

**Comment by umutbalkan** [comment]
mobile view is still an issue, 

1. right sidebar and font size is pretty large compared to a mobile display res. better make it as an "hamburger menu" to completely hide it.

2. tech tree doesn't fit the screen in horizontal way, also cannot select or change the civilizations from the top down menu since it doesn't fit the screen.

3. Unit names can't fit in their box

4. Unable to deselect an already selected unit / unable to close the description box

page generally does not fit horizontally.


![IMG_1314](https://user-images.githubusercontent.com/8284138/80230767-0dce6f00-865b-11ea-9ac4-37375dd43c33.PNG)

![img2](https://user-images.githubusercontent.com/8284138/80231295-dad8ab00-865b-11ea-997c-9c187db9c34e.jpeg)
