### ISSUE TITLE
Inca Slinger shows Crossbowman tooltip

### ISSUE THREAD

**Issue by Tilanus** [SiegeEngineers/aoe2techtree#32]
See title.

Greetings from FE! We love your techtree. 👍

**Comment by HSZemi** [comment]
Thank you for the nice words and the bug report!

The help text of the Imperial Camel Rider was also wrong, both should now be fixed with a9d3b9eaf88aa181b6fec5b1a134c6c4c63e6407.
Strangely, the underlying issue affects exclusively units that were introduced with the Forgotten Empires expansion :upside_down_face:
