### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by umutbalkan** [SiegeEngineers/aoe2techtree#35]
mobile view is still an issue,  #24

1. right sidebar and font size is pretty large compared to a mobile display res. better make it as an "hamburger menu" to completely hide it.

2. tech tree doesn't fit the screen in horizontal way, also cannot select or change the civilizations from the top down menu since it doesn't fit the screen.

3. Unit names can't fit in their box

4. Unable to deselect an already selected unit / unable to close the description box

page generally does not fit horizontally.

[tree]( https://user-images.githubusercontent.com/8284138/80230767-0dce6f00-865b-11ea-9ac4-37375dd43c33.PNG)

[civ menu / sidebar](https://user-images.githubusercontent.com/8284138/80231295-dad8ab00-865b-11ea-997c-9c187db9c34e.jpeg)

**Comment by HSZemi** [comment]
There is no right sidebar? I assume you mean the left sidebar. Also, I assume you mean the page does not fit vertically.

You should be able to close the description box by tapping on the light brown background area.

There should be no need for a "hamburger" menu since the sidebar is not fixed to the side on small screens, so it should just slide out of the way when you swipe left.

There is a point at which a screen becomes so small it makes no sense anymore to try to display a recreation of the in-game tech tree, and I am afraid your device has surpassed that point.

What web browser are you using? It looks fine on Chrome and Firefox on Android (see attached images).

Maybe you are able to create a pull request that fixes the display issues for your device but keeps the design stable for bigger devices?

![Screenshot_20200424-210749](https://user-images.githubusercontent.com/3027817/80248779-e5ea0600-8670-11ea-9276-1ab2efcd4184.png)
![Screenshot_20200424-210758](https://user-images.githubusercontent.com/3027817/80248784-e8e4f680-8670-11ea-9e1d-9a249c6ce843.png)

**Comment by tigigti** [comment]
Since the last update it doesn't fit vertically anymore. Also the age icons are really big compare to the tech icons. 
![Screenshot_20200512-040435_Chrome](https://user-images.githubusercontent.com/28649066/81630418-d0f9ca80-9405-11ea-99a9-614ff7b623bb.jpg)

**Comment by HSZemi** [comment]
@tigigti I just pushed an update, could you check if the worst issues are resolved now?

**Comment by pardoman** [comment]
I checked on mobile and it looks better.

**Comment by tigigti** [comment]
Yes I can confirm that, only the text is beyond the icons bounds now, but that is a negligible issue

**Comment by HSZemi** [comment]
It's a tradeoff between legible text and text that fits inside the boundaries :shrug:
