### ISSUE TITLE
Incorrect Town Center cost

### ISSUE THREAD

**Issue by dcabrera88** [SiegeEngineers/aoe2techtree#64]
Town Center Cost is incorrectly displayed as costing only 275W. The correct cost should be 275W 100S.

In data.json there are two buildings that use the LanguageNameId 5164 corresponding to the Town Center.  Buliding ID 71 (line 186) and Building ID 109 (line 357). Building ID 71 shows the cost of the TC to be only 275W while building ID 109 shows the correct 275W 100S value.

This value is used as a constant in techtree.js to define the TOWN CENTER (line 31).

**Comment by HSZemi** [comment]
You are right, thank you for your bug report.

I am not sure anymore why we collect the data of both Town Center instances, but only use one in the end. Sadly, the melee and pierce armor values of those two units differ a bit.

Since building a Town Center costs the 100 stone, but repairing it does not cost stone, I suspect those two units might have something to do with that. I will investigate and then try to fix the issue properly.

**Comment by HSZemi** [comment]
ID 109 does indeed look like the right unit. Thanks again!
ed9d8f25bd282899eceb0f6e63ef7f6472d13bf7
